### ISSUE TITLE
FEC exports are not available for France Overseas territories

### ISSUE THREAD

**Issue by madmath03** [britlog/erpnext_france#3]
The FEC properties from this plugin are only available for companies registered in France, but they should be available for France Overseas territories like Guadeloupe, Martinique, Guyane, etc...

**Comment by britlog** [comment]
Hi, 
There is no test about the country, you just have to install the app and it must work.
What ERPNext version do you use ?
You don't get access to the FEC button ?

**Comment by madmath03** [comment]
Hi,
After looking a bit more into the details on our side, I think I have created the issue in the wrong place.

The thing is, we have a company in Guadeloupe but ERPNext only allows access to the "Plan Comptable General" when the country of the company is France (see screenshots).

I thought that the French accounts template was part of this plugin but it's actually part of ERPNext itself. Sorry for the mistake 😭 
I will close this, create a new issue directly in ERPNext and probably open a subject on the forum. Feel free to join in if you have an idea 😉 

* France:
![image](https://user-images.githubusercontent.com/6967675/62212085-4ed17580-b3a0-11e9-9404-ae78cf9362f2.png)
* Guadeloupe
![image](https://user-images.githubusercontent.com/6967675/62212148-758fac00-b3a0-11e9-84d7-b164fa3b4aec.png)

**Comment by madmath03** [comment]
For reference :
* https://github.com/frappe/erpnext/issues/18539
* https://discuss.erpnext.com/t/france-chart-of-accounts-and-regional-settings-not-applied-to-france-overseas-territories/51336
